### ISSUE TITLE
subset_ids on rearrange

### ISSUE THREAD

**Issue by bloodbare** [plone/plone.app.content#52]
The mockup pattern sends the variable subsetIds to rearrange the folder_contents table and the https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/contents/rearrange.py#L46 get the subset_ids. Is there any reason for that ?

@jensens

**Comment by vangheem** [comment]
That is ordering, not rearrange. Subset ids are meant to prevent ordering when the order has changed since the user has last looked. You can't order it if the order the user is changing doesn't start from the same position.

Is there something wrong you notice about it? I have noticed issues with ordering on the root of the site because the order might vary with all the portal tools, etc being on the site root.

**Comment by bloodbare** [comment]
when the mockup pattern calls fc-itemOrder the function that is called is rearrange.ItemOrderActionView. The mockup pattern sends a var with the supposed current ids with the name subsetIds but the function tries to get from the request a var calles subset_ids. I just saw when I was debugging for another problem and I thought it may be a mistake.

**Comment by vangheem** [comment]
I think this is fixed in latest mockup. I'm closing now. Feel free to re-open.

**Comment by ewohnlich** [comment]
FYI I am getting this issue in Plone 5.0.5. It is mainly an issue on the root, because OFS will otherwise pick a value of subset_ids for you. But on the root you have a lot of hidden objects like portal_* and MailHost and without subset_ids it will move your content by delta relative to all of that stuff - and to the end user it sometimes looks like it hasn't moved at all.

In addition to getting "subsetIds" instead of "subset_ids" from the request, you must also pass your subset_ids variable to ordering.moveObjectsByDelta
